services:
  portfolio:
    build: .
    container_name: portofolio
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - shared_net

networks:
  shared_net:
    external: true
